"""Pydantic schemas for Bounded Tool-Calling Payment Recovery Agent.

Day 10 deliverable: schema-validated allow-listed tools, redacted contexts,
structured recovery plans, executor guard validation, and audit traces.
"""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field


# ============================================================================
# 1. TOOL DEFINITION & CATALOG SCHEMAS
# ============================================================================


class ToolParameterSchema(BaseModel):
    """Schema definition for a tool's parameter."""

    name: str
    type: str
    description: str
    required: bool = True
    default: Any = None


class ToolDefinitionSchema(BaseModel):
    """Allow-listed tool metadata and input specification."""

    name: str
    description: str
    parameters: list[ToolParameterSchema] = Field(default_factory=list)
    category: str = "read_only"  # read_only | planning | execution_guard | audit
    safety_level: str = "strictly_bounded"
    read_only: bool = True


class AgentToolCatalogResponse(BaseModel):
    """Catalog of all allow-listed tools and architectural guardrails."""

    tools: list[ToolDefinitionSchema]
    guardrails: list[str]
    agent_version: str = "v1.0.0"


# ============================================================================
# 2. REDACTED CONTEXT SCHEMAS (PII-SAFE)
# ============================================================================


class RedactedCustomerProfile(BaseModel):
    """PII-redacted customer behavioral profile."""

    external_customer_id: str
    masked_email: str | None = None
    masked_phone: str | None = None
    risk_segment: str = "STANDARD"
    behavioral_segment: str = "NEW_CUSTOMER"
    success_rate: float = 0.0
    recovery_rate: float = 0.0
    recent_failure_streak: int = 0
    risk_score: float = 0.1
    preferred_payment_method: str | None = None
    total_transactions: int = 0
    total_spent: float = 0.0


class RedactedAttemptRecord(BaseModel):
    """Redacted record of a single prior payment attempt."""

    attempt_number: int
    payment_method: str
    gateway: str | None = None
    failure_code: str | None = None
    created_at: str | None = None


class RedactedTransactionContext(BaseModel):
    """Safe, redacted transaction context presented to the agent."""

    transaction_id: str
    merchant_id: str
    amount: float
    currency: str = "INR"
    status: str
    current_attempt_count: int
    failure_code: str | None = None
    failure_category: str | None = None
    is_recoverable: bool = True
    attempts_history: list[RedactedAttemptRecord] = Field(default_factory=list)
    customer: RedactedCustomerProfile | None = None


# ============================================================================
# 3. TOOL INVOCATION & SCORING SCHEMAS
# ============================================================================


class ToolCallRequest(BaseModel):
    """Direct execution request for a single allow-listed tool."""

    tool_name: str
    arguments: dict[str, Any] = Field(default_factory=dict)


class ToolCallResult(BaseModel):
    """Result of a single tool invocation."""

    tool_name: str
    success: bool
    data: dict[str, Any] = Field(default_factory=dict)
    error: str | None = None
    execution_time_ms: float = 0.0


class CandidateScoreEvidence(BaseModel):
    """Scoring evidence for a candidate recovery action."""

    action_type: str
    probability: float
    expected_value: float
    gross_expected_value: float
    execution_cost: float
    friction_penalty: float
    channel: str
    rank: int
    selected: bool
    reason: str = ""


class ScoreCandidatesResult(BaseModel):
    """Output of candidate scoring tool."""

    transaction_id: str
    failure_category: str
    candidates: list[CandidateScoreEvidence]
    best_action: CandidateScoreEvidence | None = None
    recommendation_summary: str = ""


# ============================================================================
# 4. RECOVERY PLAN & EXECUTION SCHEMAS
# ============================================================================


class AgentPlanRequest(BaseModel):
    """Request to create a structured recovery plan."""

    transaction_id: str
    chosen_action: str
    confidence_score: float = Field(default=0.85, ge=0.0, le=1.0)
    reason_codes: list[str] = Field(default_factory=list)
    fallback_action: str | None = None
    parameters: dict[str, Any] = Field(default_factory=dict)


class AgentRecoveryPlan(BaseModel):
    """Draft or approved recovery plan generated by the agent."""

    recovery_plan_id: str
    transaction_id: str
    chosen_action: str
    confidence_score: float
    expected_value: float
    predicted_probability: float
    fallback_action: str | None = None
    reason_codes: list[str] = Field(default_factory=list)
    parameters: dict[str, Any] = Field(default_factory=dict)
    idempotency_key: str
    status: str = "DRAFT"  # DRAFT | APPROVED | REFUSED | EXECUTED
    created_at: str


class AgentExecutionRequest(BaseModel):
    """Request sent to the executor validation guard."""

    transaction_id: str
    recovery_plan_id: str
    idempotency_key: str | None = None


class AgentExecutionResult(BaseModel):
    """Result returned by the pre-execution guard."""

    disposition: str  # APPROVED | QUEUED | REFUSED | BLOCKED
    execution_id: str
    recovery_plan_id: str
    transaction_id: str
    action_type: str
    message: str
    guard_checks: dict[str, bool] = Field(default_factory=dict)
    next_scheduled_at: str | None = None


# ============================================================================
# 5. AUDIT EXPLANATION SCHEMAS
# ============================================================================


class AgentExplanationRequest(BaseModel):
    """Request to write explainable multi-stakeholder audit records."""

    transaction_id: str
    recovery_plan_id: str | None = None
    explanation_summary: str
    customer_message: str
    merchant_notes: str
    reason_codes: list[str] = Field(default_factory=list)


class AgentExplanationResult(BaseModel):
    """Confirmation of audit explanation persistence."""

    audit_id: str
    transaction_id: str
    explanation_summary: str
    customer_message: str
    merchant_notes: str
    compliance_advisory: str | None = None
    reason_codes: list[str]
    recorded_at: str
    explanation_source: str = "template"


# ============================================================================
# 6. INVESTIGATION TRACE & AGENT API SCHEMAS
# ============================================================================


class AgentStepTrace(BaseModel):
    """Detailed trace of an individual agent step and tool invocation."""

    step_number: int
    thought: str
    tool_name: str
    tool_arguments: dict[str, Any]
    tool_result: dict[str, Any]
    timestamp: str
    duration_ms: float = 0.0


class AgentInvestigationRequest(BaseModel):
    """Request to trigger full agent investigation on a failed transaction."""

    transaction_id: str = Field(description="UUID of the failed transaction")
    override_failure_code: str | None = Field(default=None, description="Optional failure code override for simulation")
    execute_bounded_action: bool = Field(default=True, description="Whether to request bounded execution if approved")


class AgentInvestigationResponse(BaseModel):
    """Complete response and decision trace from the Payment Recovery Agent."""

    investigation_id: str
    transaction_id: str
    status: str  # COMPLETED | STOPPED | NEEDS_REVIEW
    failure_category: str
    failure_code: str
    chosen_action: str
    expected_value: float
    predicted_probability: float
    execution_disposition: str
    customer_explanation: str
    merchant_explanation: str
    compliance_notes: str | None = None
    recovery_plan: AgentRecoveryPlan | None = None
    steps: list[AgentStepTrace] = Field(default_factory=list)
    audit_records: list[str] = Field(default_factory=list)
    total_duration_ms: float
