"""Canonical Failure Taxonomy — Single Source of Truth for Payment Failure Codes.

Defines the authoritative catalog of payment failure codes, classifications,
permitted recovery actions, retry bounds, delays, messages, and compliance notes.
All failure intelligence, policy, simulation, decision engine, and evaluation
subsystems import from this canonical module.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Any


class CanonicalCategory(str, Enum):
    HARD_FAILURE = "HARD_FAILURE"
    PAYMENT_METHOD = "PAYMENT_METHOD"
    CUSTOMER_ACTION = "CUSTOMER_ACTION"
    TEMPORARY = "TEMPORARY"


@dataclass(frozen=True)
class FailureDefinition:
    code: str
    category: CanonicalCategory
    recoverable: bool
    permitted_actions: tuple[str, ...]
    suggested_action: str
    max_retries: int
    delay_seconds: int
    customer_message: str
    merchant_reason: str
    compliance_note: str
    description: str = ""
    typical_gateways: tuple[str, ...] = ()
    typical_methods: tuple[str, ...] = ()
    alternative_methods: tuple[str, ...] = ()
    default_error_message: str = ""


CANONICAL_FAILURE_TAXONOMY: dict[str, FailureDefinition] = {
    # ------------------------------------------------------------------------
    # 1. HARD FAILURES (Terminal stops: 0 retries, strictly STOP_RECOVERY)
    # ------------------------------------------------------------------------
    "BLOCKED_CARD": FailureDefinition(
        code="BLOCKED_CARD",
        category=CanonicalCategory.HARD_FAILURE,
        recoverable=False,
        permitted_actions=("STOP_RECOVERY",),
        suggested_action="STOP_RECOVERY",
        max_retries=0,
        delay_seconds=0,
        customer_message="Your card has been blocked by your bank. Please use an alternative card or payment method.",
        merchant_reason="Issuing bank reported card as lost, stolen, or frozen. Immediate terminal stop mandated to prevent chargebacks.",
        compliance_note="Card network rule: Do not re-attempt transactions on hotlisted or stolen cards. Zero retry tolerance.",
        description="Card has been reported lost, stolen, frozen, or permanently blocked by issuing bank.",
        typical_gateways=("RAZORPAY", "STRIPE", "PAYU", "VISA_MASTERCARD"),
        typical_methods=("CARD",),
        alternative_methods=("UPI", "NETBANKING"),
        default_error_message="The card has been blocked by the issuing bank. Please use another payment method.",
    ),
    "INVALID_ACCOUNT": FailureDefinition(
        code="INVALID_ACCOUNT",
        category=CanonicalCategory.HARD_FAILURE,
        recoverable=False,
        permitted_actions=("STOP_RECOVERY",),
        suggested_action="STOP_RECOVERY",
        max_retries=0,
        delay_seconds=0,
        customer_message="The destination or payment account could not be found. Please verify your details or use another payment method.",
        merchant_reason="Account identifier rejected by core banking switch or NPCI as non-existent.",
        compliance_note="Account verification failed. Ensure valid beneficiary details.",
        description="Bank account number or VPA handle does not exist or has been permanently closed.",
        typical_gateways=("NPCI", "RAZORPAY", "CASHFREE", "BILLDESK"),
        typical_methods=("UPI", "NETBANKING"),
        alternative_methods=("UPI", "CARD"),
        default_error_message="Invalid account details or VPA handle.",
    ),
    "FRAUD_REJECTED": FailureDefinition(
        code="FRAUD_REJECTED",
        category=CanonicalCategory.HARD_FAILURE,
        recoverable=False,
        permitted_actions=("STOP_RECOVERY",),
        suggested_action="STOP_RECOVERY",
        max_retries=0,
        delay_seconds=0,
        customer_message="This payment could not be processed due to security and risk verification policies.",
        merchant_reason="Risk engine flagged high-probability anomaly or blacklisted entity. Recovery attempts suppressed.",
        compliance_note="Security rule: suppress automated recovery triggers on fraud declines.",
        description="Transaction flagged and rejected by fraud detection system, risk scoring engine, or AML filter.",
        typical_gateways=("STRIPE", "RAZORPAY", "VISA_RISK", "CYBERSOURCE"),
        typical_methods=("CARD", "UPI", "WALLET", "NETBANKING", "BNPL"),
        alternative_methods=(),
        default_error_message="Transaction declined by security risk checks.",
    ),
    "EXPIRED_CARD": FailureDefinition(
        code="EXPIRED_CARD",
        category=CanonicalCategory.HARD_FAILURE,
        recoverable=False,
        permitted_actions=("STOP_RECOVERY",),
        suggested_action="STOP_RECOVERY",
        max_retries=0,
        delay_seconds=0,
        customer_message="Your card has expired. Please enter details of a valid card or pay via UPI.",
        merchant_reason="Card expiry date passed. Retry on same instrument is impossible.",
        compliance_note="Card tokenization guidelines require valid active card metadata.",
        description="Card validity date is in the past.",
        typical_gateways=("STRIPE", "RAZORPAY", "PAYU", "HDFC_SMARTHUB"),
        typical_methods=("CARD",),
        alternative_methods=("UPI", "CARD", "NETBANKING"),
        default_error_message="The payment card has expired.",
    ),
    "LIMIT_EXCEEDED_HARD": FailureDefinition(
        code="LIMIT_EXCEEDED_HARD",
        category=CanonicalCategory.HARD_FAILURE,
        recoverable=False,
        permitted_actions=("STOP_RECOVERY",),
        suggested_action="STOP_RECOVERY",
        max_retries=0,
        delay_seconds=0,
        customer_message="The maximum permissible spending limit for this account has been reached.",
        merchant_reason="Permanent card credit ceiling or bank account lifecycle cap reached.",
        compliance_note="Hard ceiling decline. Re-attempts will be consistently rejected.",
        description="Permanent credit line exhausted or monthly maximum transaction limit reached.",
        typical_gateways=("RAZORPAY", "STRIPE", "PAYU"),
        typical_methods=("CARD", "UPI"),
        alternative_methods=("NETBANKING", "UPI"),
        default_error_message="Account limits exceeded for this cycle.",
    ),
    "ACCOUNT_CLOSED": FailureDefinition(
        code="ACCOUNT_CLOSED",
        category=CanonicalCategory.HARD_FAILURE,
        recoverable=False,
        permitted_actions=("STOP_RECOVERY",),
        suggested_action="STOP_RECOVERY",
        max_retries=0,
        delay_seconds=0,
        customer_message="The specified bank account is inactive or closed. Please select a different bank account.",
        merchant_reason="Bank returned account inactive/closed state code.",
        compliance_note="Terminal account status.",
        description="The payer bank account is closed or dormant.",
        typical_gateways=("NPCI", "RAZORPAY", "BILLDESK"),
        typical_methods=("UPI", "NETBANKING"),
        alternative_methods=("UPI", "CARD"),
        default_error_message="Bank account has been closed.",
    ),
    "BLACKLISTED_VPA": FailureDefinition(
        code="BLACKLISTED_VPA",
        category=CanonicalCategory.HARD_FAILURE,
        recoverable=False,
        permitted_actions=("STOP_RECOVERY",),
        suggested_action="STOP_RECOVERY",
        max_retries=0,
        delay_seconds=0,
        customer_message="This UPI handle cannot be used. Please provide a different UPI ID or card.",
        merchant_reason="NPCI risk switch reported VPA as blacklisted/compromised.",
        compliance_note="NPCI security block.",
        description="UPI VPA handle has been blacklisted by NPCI or bank for spam/abuse.",
        typical_gateways=("NPCI", "BHIM"),
        typical_methods=("UPI",),
        alternative_methods=("CARD", "NETBANKING"),
        default_error_message="UPI VPA is blacklisted.",
    ),
    "STOLEN_CARD": FailureDefinition(
        code="STOLEN_CARD",
        category=CanonicalCategory.HARD_FAILURE,
        recoverable=False,
        permitted_actions=("STOP_RECOVERY",),
        suggested_action="STOP_RECOVERY",
        max_retries=0,
        delay_seconds=0,
        customer_message="Payment cannot be processed. Please use an alternate card.",
        merchant_reason="Stolen card match in issuer directory.",
        compliance_note="Strict prohibition of re-attempts on stolen cards.",
        description="Card identified in hotlist database as stolen.",
        typical_gateways=("STRIPE", "CYBERSOURCE", "VISA"),
        typical_methods=("CARD",),
        alternative_methods=("UPI",),
        default_error_message="Stolen card reported.",
    ),
    "RESTRICTED_CARD": FailureDefinition(
        code="RESTRICTED_CARD",
        category=CanonicalCategory.HARD_FAILURE,
        recoverable=False,
        permitted_actions=("STOP_RECOVERY",),
        suggested_action="STOP_RECOVERY",
        max_retries=0,
        delay_seconds=0,
        customer_message="Usage restrictions prevent this card from being used for this purchase.",
        merchant_reason="Issuer returned card restricted code.",
        compliance_note="Issuer policy stop.",
        description="Card has administrative restrictions applied by issuer.",
        typical_gateways=("RAZORPAY", "PAYU"),
        typical_methods=("CARD",),
        alternative_methods=("UPI", "NETBANKING"),
        default_error_message="Card has administrative restrictions.",
    ),

    # ------------------------------------------------------------------------
    # 2. CUSTOMER ACTION FAILURES (Recoverable through customer interaction)
    # ------------------------------------------------------------------------
    "OTP_TIMEOUT": FailureDefinition(
        code="OTP_TIMEOUT",
        category=CanonicalCategory.CUSTOMER_ACTION,
        recoverable=True,
        permitted_actions=("CUSTOMER_NOTIFICATION", "PAYMENT_LINK", "SWITCH_TO_UPI"),
        suggested_action="CUSTOMER_NOTIFICATION",
        max_retries=2,
        delay_seconds=15,
        customer_message="The OTP entered has expired or was not submitted in time. We've sent a quick retry link.",
        merchant_reason="Customer missed the OTP verification window. High recovery potential with instant push/SMS prompt.",
        compliance_note="RBI 2-Factor Authentication (2FA) verification window timeout.",
        description="SMS or in-app One Time Password expired before submission.",
        typical_gateways=("RAZORPAY", "PAYU", "CASHFREE", "HDFC_SMARTHUB"),
        typical_methods=("CARD", "NETBANKING"),
        alternative_methods=("UPI", "CARD"),
        default_error_message="Authentication OTP expired or was not entered in time.",
    ),
    "OTP_EXPIRED": FailureDefinition(
        code="OTP_EXPIRED",
        category=CanonicalCategory.CUSTOMER_ACTION,
        recoverable=True,
        permitted_actions=("CUSTOMER_NOTIFICATION", "PAYMENT_LINK", "SWITCH_TO_UPI"),
        suggested_action="CUSTOMER_NOTIFICATION",
        max_retries=2,
        delay_seconds=60,
        customer_message="Your one-time password expired before entry. Please request a new OTP to finalize payment.",
        merchant_reason="Customer timed out on 3DS authentication challenge. Send prompt notification or checkout link.",
        compliance_note="Mandatory two-factor authentication (2FA) verification window expired.",
        description="Customer 3DS OTP expired or dropped during authentication.",
        typical_gateways=("RAZORPAY", "PAYU", "STRIPE"),
        typical_methods=("CARD", "NETBANKING"),
        alternative_methods=("UPI", "CARD"),
        default_error_message="Authentication OTP expired or was not entered in time.",
    ),
    "3DS_FAILURE": FailureDefinition(
        code="3DS_FAILURE",
        category=CanonicalCategory.CUSTOMER_ACTION,
        recoverable=True,
        permitted_actions=("CUSTOMER_NOTIFICATION", "PAYMENT_LINK", "SWITCH_TO_UPI"),
        suggested_action="CUSTOMER_NOTIFICATION",
        max_retries=2,
        delay_seconds=20,
        customer_message="Your card authentication step was interrupted. Please complete verification on your bank app or try again.",
        merchant_reason="ACS server challenge not completed. Triggering smart notification or hosted recovery link.",
        compliance_note="EMV 3DS 2.x authentication drop-off.",
        description="3D Secure authentication dropped, biometric failed, or challenge canceled by customer.",
        typical_gateways=("STRIPE", "RAZORPAY", "VISA_3DS", "MASTERCARD_ID_CHECK"),
        typical_methods=("CARD",),
        alternative_methods=("UPI", "NETBANKING"),
        default_error_message="3D Secure verification failed.",
    ),
    "INSUFFICIENT_FUNDS": FailureDefinition(
        code="INSUFFICIENT_FUNDS",
        category=CanonicalCategory.CUSTOMER_ACTION,
        recoverable=True,
        permitted_actions=("CUSTOMER_NOTIFICATION", "PAYMENT_LINK", "SWITCH_TO_UPI"),
        suggested_action="CUSTOMER_NOTIFICATION",
        max_retries=2,
        delay_seconds=60,
        customer_message="There was insufficient balance in the selected account. Please use another account or card.",
        merchant_reason="Payer account balance check failed. Prompting user with flexible multi-option payment link.",
        compliance_note="Ensure respectful customer notification without broadcasting balance details.",
        description="Payer account or credit limit currently lacks adequate balance.",
        typical_gateways=("NPCI", "RAZORPAY", "STRIPE", "PAYU"),
        typical_methods=("CARD", "UPI", "NETBANKING", "WALLET"),
        alternative_methods=("UPI", "CARD", "NETBANKING", "BNPL"),
        default_error_message="Insufficient funds in the selected account.",
    ),
    "INCORRECT_PIN": FailureDefinition(
        code="INCORRECT_PIN",
        category=CanonicalCategory.CUSTOMER_ACTION,
        recoverable=True,
        permitted_actions=("CUSTOMER_NOTIFICATION", "PAYMENT_LINK"),
        suggested_action="CUSTOMER_NOTIFICATION",
        max_retries=2,
        delay_seconds=30,
        customer_message="The UPI PIN or MPIN entered was incorrect. Please try again with the correct PIN.",
        merchant_reason="NPCI rejected due to MPIN mismatch. Customer must re-authenticate.",
        compliance_note="NPCI PIN retry policy: multiple incorrect attempts lock handle for 24h.",
        description="Incorrect UPI MPIN or ATM PIN entered by customer.",
        typical_gateways=("NPCI", "BHIM", "PHONEPE", "GPAY"),
        typical_methods=("UPI", "CARD"),
        alternative_methods=("CARD", "NETBANKING"),
        default_error_message="Incorrect UPI PIN / security PIN entered.",
    ),
    "USER_CANCELLED": FailureDefinition(
        code="USER_CANCELLED",
        category=CanonicalCategory.CUSTOMER_ACTION,
        recoverable=True,
        permitted_actions=("CUSTOMER_NOTIFICATION", "PAYMENT_LINK"),
        suggested_action="PAYMENT_LINK",
        max_retries=1,
        delay_seconds=300,
        customer_message="We noticed you cancelled your order. If this was an accident, you can complete payment with one click.",
        merchant_reason="User initiated checkout cancellation. Send gentle recovery link with order summary.",
        compliance_note="Cart abandonment recovery communication rules apply.",
        description="Customer explicitly backed out or dismissed payment checkout sheet.",
        typical_gateways=("RAZORPAY", "STRIPE", "PAYU", "CASHFREE"),
        typical_methods=("UPI", "CARD", "NETBANKING", "WALLET", "BNPL"),
        alternative_methods=("UPI", "CARD", "WALLET"),
        default_error_message="Transaction was cancelled by the customer.",
    ),
    "INVALID_CVV": FailureDefinition(
        code="INVALID_CVV",
        category=CanonicalCategory.CUSTOMER_ACTION,
        recoverable=True,
        permitted_actions=("CUSTOMER_NOTIFICATION", "PAYMENT_LINK"),
        suggested_action="CUSTOMER_NOTIFICATION",
        max_retries=2,
        delay_seconds=10,
        customer_message="The CVV code entered was incorrect. Please re-enter your card details.",
        merchant_reason="CVV validation mismatch at gateway level.",
        compliance_note="Do not store or log raw CVV values (PCI-DSS requirement).",
        description="Card Verification Value (CVV/CVC) did not match issuer records.",
        typical_gateways=("STRIPE", "RAZORPAY", "PAYU"),
        typical_methods=("CARD",),
        alternative_methods=("UPI", "CARD"),
        default_error_message="Invalid CVV entered.",
    ),
    "AUTHENTICATION_FAILED": FailureDefinition(
        code="AUTHENTICATION_FAILED",
        category=CanonicalCategory.CUSTOMER_ACTION,
        recoverable=True,
        permitted_actions=("CUSTOMER_NOTIFICATION", "PAYMENT_LINK", "SWITCH_TO_UPI"),
        suggested_action="CUSTOMER_NOTIFICATION",
        max_retries=2,
        delay_seconds=0,
        customer_message="Authentication could not be completed. Please retry or authorize via your banking app.",
        merchant_reason="Customer dropped off 3DS redirect page or failed biometric verification.",
        compliance_note="Customer authorization incomplete.",
        description="General 3DS authentication failure or customer abandonment.",
        typical_gateways=("RAZORPAY", "STRIPE"),
        typical_methods=("CARD", "UPI"),
        alternative_methods=("UPI", "CARD"),
        default_error_message="Authentication failed.",
    ),

    # ------------------------------------------------------------------------
    # 3. PAYMENT METHOD FAILURES (Recoverable via Method Switch / Alternate Instrument)
    # ------------------------------------------------------------------------
    "CARD_DECLINED": FailureDefinition(
        code="CARD_DECLINED",
        category=CanonicalCategory.PAYMENT_METHOD,
        recoverable=True,
        permitted_actions=("SWITCH_TO_UPI", "PAYMENT_LINK", "SWITCH_TO_NETBANKING"),
        suggested_action="SWITCH_TO_UPI",
        max_retries=1,
        delay_seconds=0,
        customer_message="Your card issuer declined the transaction. Switching to UPI or NetBanking will complete your purchase instantly.",
        merchant_reason="Bank issuer decline (ISO 05 Do Not Honor). Avoid re-hammering same card; switch to high-success UPI channel.",
        compliance_note="RBI guidelines on card domestic/international e-commerce flags.",
        description="Card issuing bank generic decline (e-commerce not enabled, issuer policy, or card tier limit).",
        typical_gateways=("RAZORPAY", "STRIPE", "PAYU", "HDFC_SMARTHUB"),
        typical_methods=("CARD",),
        alternative_methods=("UPI", "NETBANKING", "WALLET"),
        default_error_message="Card declined by issuer. Online transactions may be disabled.",
    ),
    "CARD_TYPE_NOT_SUPPORTED": FailureDefinition(
        code="CARD_TYPE_NOT_SUPPORTED",
        category=CanonicalCategory.PAYMENT_METHOD,
        recoverable=True,
        permitted_actions=("SWITCH_TO_UPI", "PAYMENT_LINK", "SWITCH_TO_NETBANKING"),
        suggested_action="SWITCH_TO_UPI",
        max_retries=1,
        delay_seconds=0,
        customer_message="This specific card type is not accepted for this merchant. Please try with UPI or another card.",
        merchant_reason="Card BIN tier rejected by acquiring rules (e.g. prepaid or non-3DS commercial).",
        compliance_note="Routing policy: enforce supported instrument filter.",
        description="Commercial, prepaid, or corporate card tier not permitted by merchant account or acquirer.",
        typical_gateways=("RAZORPAY", "STRIPE", "PAYU"),
        typical_methods=("CARD",),
        alternative_methods=("UPI", "NETBANKING"),
        default_error_message="This specific card brand/type is not supported for this checkout.",
    ),
    "MANDATE_FAILED": FailureDefinition(
        code="MANDATE_FAILED",
        category=CanonicalCategory.PAYMENT_METHOD,
        recoverable=True,
        permitted_actions=("PAYMENT_LINK", "SWITCH_TO_UPI"),
        suggested_action="PAYMENT_LINK",
        max_retries=2,
        delay_seconds=86400,
        customer_message="Your auto-debit subscription payment could not be processed. Please settle with a one-time link or update your mandate.",
        merchant_reason="Recurring mandate execution failed. Dispatching one-click invoice / payment link.",
        compliance_note="RBI e-Mandate circular: Pre-debit notification required 24h prior to retry.",
        description="Recurring subscription e-mandate debit rejected or mandate authorization expired.",
        typical_gateways=("RAZORPAY", "STRIPE", "BILLDESK"),
        typical_methods=("CARD", "UPI", "NETBANKING"),
        alternative_methods=("UPI", "CARD"),
        default_error_message="Recurring mandate setup or presentation failed.",
    ),
    "INTERNATIONAL_NOT_ALLOWED": FailureDefinition(
        code="INTERNATIONAL_NOT_ALLOWED",
        category=CanonicalCategory.PAYMENT_METHOD,
        recoverable=True,
        permitted_actions=("SWITCH_TO_UPI", "PAYMENT_LINK"),
        suggested_action="SWITCH_TO_UPI",
        max_retries=1,
        delay_seconds=0,
        customer_message="International/cross-border transactions are not enabled on your card. Please use a domestic card or UPI.",
        merchant_reason="Payer card lacks international e-commerce activation.",
        compliance_note="FEMA & cross-border merchant category constraints.",
        description="International transactions or cross-border currency conversion disabled on payer card.",
        typical_gateways=("STRIPE", "RAZORPAY"),
        typical_methods=("CARD",),
        alternative_methods=("UPI", "DOMESTIC_CARD"),
        default_error_message="International transactions disabled on card.",
    ),
    "ECOMMERCE_DISABLED": FailureDefinition(
        code="ECOMMERCE_DISABLED",
        category=CanonicalCategory.PAYMENT_METHOD,
        recoverable=True,
        permitted_actions=("SWITCH_TO_UPI", "PAYMENT_LINK"),
        suggested_action="SWITCH_TO_UPI",
        max_retries=1,
        delay_seconds=0,
        customer_message="Online transactions are disabled for your card. Enable it in your bank app or pay instantly via UPI.",
        merchant_reason="RBI e-commerce card control toggle is off. UPI switch provides frictionless conversion.",
        compliance_note="RBI Card Controls Mandate 2020.",
        description="Online e-commerce transactions are toggled off in payer's mobile banking app.",
        typical_gateways=("RAZORPAY", "PAYU", "HDFC_SMARTHUB"),
        typical_methods=("CARD",),
        alternative_methods=("UPI", "NETBANKING"),
        default_error_message="E-commerce transactions disabled on card.",
    ),
    "TOKENIZATION_ERROR": FailureDefinition(
        code="TOKENIZATION_ERROR",
        category=CanonicalCategory.PAYMENT_METHOD,
        recoverable=True,
        permitted_actions=("PAYMENT_LINK", "SWITCH_TO_UPI"),
        suggested_action="PAYMENT_LINK",
        max_retries=1,
        delay_seconds=0,
        customer_message="Saved card security token expired. Please enter your card details again or use UPI.",
        merchant_reason="Card-on-File token invalid. Customer must re-tokenize or use alternative method.",
        compliance_note="RBI Card-on-File Tokenization (CoFT) protocol.",
        description="Card token (CoF) expired, deleted, or cryptogram validation failed.",
        typical_gateways=("RAZORPAY", "STRIPE", "PAYU"),
        typical_methods=("CARD",),
        alternative_methods=("UPI", "CARD"),
        default_error_message="Tokenization cryptogram verification failed.",
    ),

    # ------------------------------------------------------------------------
    # 4. TEMPORARY FAILURES (Transient infrastructure blips - smart retry)
    # ------------------------------------------------------------------------
    "TIMEOUT": FailureDefinition(
        code="TIMEOUT",
        category=CanonicalCategory.TEMPORARY,
        recoverable=True,
        permitted_actions=("DELAYED_RETRY", "RETRY_SAME_METHOD"),
        suggested_action="DELAYED_RETRY",
        max_retries=3,
        delay_seconds=60,
        customer_message="The payment took longer than expected to connect to your bank. We are verifying and retrying.",
        merchant_reason="Upstream gateway/bank HTTP socket timeout. Safe for automated backoff retry.",
        compliance_note="Check transaction status inquiry before firing live retry to prevent double debits.",
        description="Acquiring gateway or upstream banking switch timed out waiting for response.",
        typical_gateways=("RAZORPAY", "STRIPE", "PAYU", "NPCI", "CASHFREE"),
        typical_methods=("UPI", "CARD", "NETBANKING", "WALLET"),
        alternative_methods=("UPI", "NETBANKING"),
        default_error_message="Gateway connection timed out while processing payment.",
    ),
    "GATEWAY_TIMEOUT": FailureDefinition(
        code="GATEWAY_TIMEOUT",
        category=CanonicalCategory.TEMPORARY,
        recoverable=True,
        permitted_actions=("DELAYED_RETRY", "RETRY_SAME_METHOD"),
        suggested_action="DELAYED_RETRY",
        max_retries=3,
        delay_seconds=60,
        customer_message="Payment service experienced a transient timeout. We are automatically resolving this for you.",
        merchant_reason="Gateway API response deadline exceeded. Transient latency; delayed retry recommended.",
        compliance_note="Check gateway payment status before re-submitting attempt.",
        description="Gateway / switch network timeout without conclusive final disposition.",
        typical_gateways=("RAZORPAY", "NPCI", "STRIPE"),
        typical_methods=("UPI", "CARD", "NETBANKING", "WALLET"),
        alternative_methods=("UPI", "CARD"),
        default_error_message="Gateway connection timed out while processing payment.",
    ),
    "BANK_UNAVAILABLE": FailureDefinition(
        code="BANK_UNAVAILABLE",
        category=CanonicalCategory.TEMPORARY,
        recoverable=True,
        permitted_actions=("DELAYED_RETRY", "SWITCH_TO_UPI"),
        suggested_action="DELAYED_RETRY",
        max_retries=3,
        delay_seconds=300,
        customer_message="Your bank's servers are temporarily offline for maintenance. We will retry your payment in a few minutes.",
        merchant_reason="Issuer CBS downtime (ISO 91). Backoff schedule required.",
        compliance_note="Respect bank scheduled maintenance windows.",
        description="Issuer core banking system (CBS) is temporarily down or undergoing maintenance.",
        typical_gateways=("NPCI", "RAZORPAY", "BILLDESK", "HDFC_SMARTHUB", "SBI_GATEWAY"),
        typical_methods=("NETBANKING", "UPI", "CARD"),
        alternative_methods=("UPI", "CARD"),
        default_error_message="Issuer bank servers are currently undergoing maintenance.",
    ),
    "NETWORK_ERROR": FailureDefinition(
        code="NETWORK_ERROR",
        category=CanonicalCategory.TEMPORARY,
        recoverable=True,
        permitted_actions=("RETRY_SAME_METHOD", "DELAYED_RETRY"),
        suggested_action="RETRY_SAME_METHOD",
        max_retries=3,
        delay_seconds=15,
        customer_message="A momentary network glitch occurred. Retrying your transaction now.",
        merchant_reason="Transient packet drop or network reset between merchant and PSP switch.",
        compliance_note="Exponential backoff with jitter recommended.",
        description="Transient TCP/TLS network error or connection reset during transaction processing.",
        typical_gateways=("RAZORPAY", "STRIPE", "PAYU", "CASHFREE"),
        typical_methods=("UPI", "CARD", "NETBANKING", "WALLET", "BNPL"),
        alternative_methods=("UPI", "CARD"),
        default_error_message="Network communication error between gateway and processor.",
    ),
    "UPI_FAILURE": FailureDefinition(
        code="UPI_FAILURE",
        category=CanonicalCategory.TEMPORARY,
        recoverable=True,
        permitted_actions=("DELAYED_RETRY", "RETRY_SAME_METHOD"),
        suggested_action="DELAYED_RETRY",
        max_retries=3,
        delay_seconds=60,
        customer_message="UPI network is experiencing high traffic. Retrying in a few moments.",
        merchant_reason="NPCI UPI switch response timeout / temporary degradation.",
        compliance_note="Monitor NPCI central heartbeat status.",
        description="NPCI switch degradation or PSP UPI application latency.",
        typical_gateways=("NPCI", "PHONEPE", "GPAY", "PAYTM"),
        typical_methods=("UPI",),
        alternative_methods=("NETBANKING", "CARD"),
        default_error_message="UPI switch is currently experiencing elevated degradation.",
    ),
    "GATEWAY_ERROR": FailureDefinition(
        code="GATEWAY_ERROR",
        category=CanonicalCategory.TEMPORARY,
        recoverable=True,
        permitted_actions=("DELAYED_RETRY", "RETRY_SAME_METHOD"),
        suggested_action="DELAYED_RETRY",
        max_retries=3,
        delay_seconds=90,
        customer_message="Payment service temporarily unavailable. We are retrying automatically.",
        merchant_reason="Aggregator returned HTTP 5xx error code.",
        compliance_note="Circuit breaker pattern enabled for gateway failure spikes.",
        description="Aggregator 500/502/503 internal server or routing error.",
        typical_gateways=("RAZORPAY", "STRIPE", "PAYU", "CASHFREE"),
        typical_methods=("UPI", "CARD", "NETBANKING", "WALLET", "BNPL"),
        alternative_methods=("UPI", "PAYMENT_LINK"),
        default_error_message="Payment provider internal processing error.",
    ),
    "BANK_SERVER_DOWN": FailureDefinition(
        code="BANK_SERVER_DOWN",
        category=CanonicalCategory.TEMPORARY,
        recoverable=True,
        permitted_actions=("DELAYED_RETRY", "SWITCH_TO_UPI"),
        suggested_action="DELAYED_RETRY",
        max_retries=3,
        delay_seconds=120,
        customer_message="Your bank's server is temporarily down for maintenance. We will retry once service resumes.",
        merchant_reason="Issuer CBS returned 91/System Error. Schedule delayed retry.",
        compliance_note="Bank maintenance window backoff required.",
        description="Core banking system (CBS) undergoing scheduled maintenance or experiencing downtime.",
        typical_gateways=("HDFC_SMARTHUB", "SBI_GATEWAY", "ICICI_PG", "NPCI"),
        typical_methods=("UPI", "NETBANKING", "CARD"),
        alternative_methods=("UPI", "PAYMENT_LINK"),
        default_error_message="Issuer bank servers are currently undergoing maintenance.",
    ),
    "RATE_LIMITED": FailureDefinition(
        code="RATE_LIMITED",
        category=CanonicalCategory.TEMPORARY,
        recoverable=True,
        permitted_actions=("DELAYED_RETRY",),
        suggested_action="DELAYED_RETRY",
        max_retries=3,
        delay_seconds=60,
        customer_message="Payment requests are processing. Please wait a moment while your payment completes.",
        merchant_reason="Upstream rate limit throttling. Apply cool-off period.",
        compliance_note="Honor Retry-After response header.",
        description="Payment gateway HTTP 429 Too Many Requests rate limit hit.",
        typical_gateways=("STRIPE", "RAZORPAY"),
        typical_methods=("CARD", "UPI"),
        alternative_methods=(),
        default_error_message="Upstream rate limit throttling.",
    ),
    "RATE_LIMIT_EXCEEDED": FailureDefinition(
        code="RATE_LIMIT_EXCEEDED",
        category=CanonicalCategory.TEMPORARY,
        recoverable=True,
        permitted_actions=("DELAYED_RETRY",),
        suggested_action="DELAYED_RETRY",
        max_retries=3,
        delay_seconds=60,
        customer_message="High traffic on payment switch. We are queuing your transaction safely.",
        merchant_reason="Gateway throttled request rate.",
        compliance_note="Respect gateway rate-limiting headers.",
        description="Payment gateway / switch rate limit exceeded.",
        typical_gateways=("RAZORPAY", "NPCI"),
        typical_methods=("CARD", "UPI"),
        alternative_methods=(),
        default_error_message="Upstream rate limit throttling.",
    ),
}

# Aliases and Gateway code mappings to Canonical codes
GATEWAY_CODE_MAP: dict[str, str] = {
    # Razorpay error codes
    "BAD_REQUEST_PAYMENT_FAILED": "CARD_DECLINED",
    "BAD_REQUEST_PAYMENT_OTP_INCORRECT": "INCORRECT_PIN",
    "BAD_REQUEST_PAYMENT_OTP_EXPIRED": "OTP_TIMEOUT",
    "BAD_REQUEST_PAYMENT_TIMED_OUT": "TIMEOUT",
    "BAD_REQUEST_PAYMENT_CARD_INSUFFICIENT_BALANCE": "INSUFFICIENT_FUNDS",
    "BAD_REQUEST_PAYMENT_CARD_INVALID_EXPIRY": "EXPIRED_CARD",
    "BAD_REQUEST_PAYMENT_CARD_BLOCKED": "BLOCKED_CARD",
    "BAD_REQUEST_PAYMENT_DECLINED_BY_BANK": "CARD_DECLINED",
    "BAD_REQUEST_PAYMENT_FRAUD_SUSPECTED": "FRAUD_REJECTED",
    "BAD_REQUEST_PAYMENT_FRAUD_DETECTED": "FRAUD_REJECTED",
    "SERVER_ERROR": "GATEWAY_ERROR",
    # NPCI / UPI Switch Response Codes
    "U30": "INVALID_ACCOUNT",
    "U69": "INSUFFICIENT_FUNDS",
    "U28": "TIMEOUT",
    "ZM": "3DS_FAILURE",
    "XB": "BANK_UNAVAILABLE",
    "XC": "RATE_LIMITED",
    "XT": "USER_CANCELLED",
    "U19": "TIMEOUT",
    # ISO 8583 Card Codes
    "05": "CARD_DECLINED",
    "14": "INVALID_ACCOUNT",
    "51": "INSUFFICIENT_FUNDS",
    "54": "EXPIRED_CARD",
    "41": "BLOCKED_CARD",
    "43": "BLOCKED_CARD",
    "91": "BANK_UNAVAILABLE",
    "96": "GATEWAY_ERROR",
}


def get_canonical_failure(code: str) -> FailureDefinition:
    """Retrieve canonical definition for any failure code, handling casing and gateway mappings."""
    if not code:
        return CANONICAL_FAILURE_TAXONOMY["TIMEOUT"]
    normalized = code.strip().upper()
    if normalized in CANONICAL_FAILURE_TAXONOMY:
        return CANONICAL_FAILURE_TAXONOMY[normalized]
    mapped_code = GATEWAY_CODE_MAP.get(normalized)
    if mapped_code and mapped_code in CANONICAL_FAILURE_TAXONOMY:
        return CANONICAL_FAILURE_TAXONOMY[mapped_code]
    # Check if category prefix or common keyword matches
    if any(term in normalized for term in ("BLOCK", "STOLEN", "FRAUD", "LOST", "EXPIRED")):
        return CANONICAL_FAILURE_TAXONOMY["FRAUD_REJECTED" if "FRAUD" in normalized else "BLOCKED_CARD"]
    if any(term in normalized for term in ("OTP", "AUTH", "CANCEL", "3DS")):
        return CANONICAL_FAILURE_TAXONOMY["OTP_TIMEOUT" if "EXPIRE" in normalized or "TIMEOUT" in normalized else "3DS_FAILURE"]
    if any(term in normalized for term in ("TIMEOUT", "GATEWAY", "NETWORK", "DOWN", "SERVER")):
        return CANONICAL_FAILURE_TAXONOMY["TIMEOUT"]
    # Safe default: PAYMENT_METHOD CARD_DECLINED
    return CANONICAL_FAILURE_TAXONOMY["CARD_DECLINED"]


def is_recoverable(code: str) -> bool:
    """Return whether a failure code is legally and technically recoverable."""
    return get_canonical_failure(code).recoverable


def get_permitted_actions(code: str) -> tuple[str, ...]:
    """Return permitted action strings for a given failure code."""
    return get_canonical_failure(code).permitted_actions
